### ISSUE TITLE
No 1_MAGIC.py file

### ISSUE THREAD

**Issue by liuyq123** [JiaqiLiZju/Nvwa#5]
Hi Jiaqi, 

Thank you for such great work!

I tried to run `0_preproc_dataset/main.sh`, but there's no file with name `1_MAGIC.py`.  Should it be `1_MAGIC_MCA.py`instead?

And get these errors after changing `1_MAGIC.py` to `1_MAGIC_MCA.py`
<img width="1219" alt="Screen Shot 2023-01-08 at 2 50 38 AM" src="https://user-images.githubusercontent.com/47292066/211185944-ebf52826-c478-40dc-8d91-511530630fa0.png">
Can you help me with these problems? Thank you!

**Comment by JiaqiLi1024** [comment]
I'm Sorry it might confuse you, because the code is more like in-house scipts for me. `1_MAGIC_MCA.py` is the script specific to the MCA dataset. 
I think you could download the provided dataset from the Nvwa website. Or, you can change the h5ad data for your own purpose. Also, there are other options, I recommend to use the software NvTK (NvwaToolKit, https://github.com/JiaqiLiZju/NvTK) for generating your own model.

**Comment by liuyq123** [comment]
Thank you!
